In [2]:
import numpy as np

In [5]:
a= np.array([1,2,3])
b= np.array([(1,2,4),(4,56,6),(90,45,67)])
print(b)
print(a)
type(a)

[[ 1  2  4]
 [ 4 56  6]
 [90 45 67]]
[1 2 3]


numpy.ndarray

In [8]:
##transpose 

In [9]:
trans=np.transpose(b)
print(trans)

[[ 1  4 90]
 [ 2 56 45]
 [ 4  6 67]]


In [10]:
##flater the array

In [11]:
b.ravel()
b.reshape

array([ 1,  2,  4,  4, 56,  6, 90, 45, 67])

In [14]:
ze=np.array([(0,0,0),(0,0,0),(0,0,0)])

In [15]:
np.append(trans,ze)

array([ 1,  4, 90,  2, 56, 45,  4,  6, 67,  0,  0,  0,  0,  0,  0,  0,  0,
        0])

In [20]:
np.concatenate((trans,ze),axis=1)

array([[ 1,  4, 90,  0,  0,  0],
       [ 2, 56, 45,  0,  0,  0],
       [ 4,  6, 67,  0,  0,  0]])

In [22]:
#empty array

In [23]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.50190390e-321],
       [1.05699242e-307, 3.11523242e-307, 5.68175493e-322]])

In [26]:
np.random.random((50,30))

array([[0.43636062, 0.47217948, 0.36002558, ..., 0.50179329, 0.10329742,
        0.58794058],
       [0.92970556, 0.96860839, 0.25649777, ..., 0.8029889 , 0.62529129,
        0.13251744],
       [0.56745414, 0.5873291 , 0.2100413 , ..., 0.28150771, 0.44915749,
        0.84892336],
       ...,
       [0.70718973, 0.28711296, 0.46571518, ..., 0.7217894 , 0.43429773,
        0.60083621],
       [0.90535843, 0.33538688, 0.4802679 , ..., 0.28230248, 0.39639082,
        0.73937668],
       [0.07768028, 0.76145173, 0.79803401, ..., 0.94162614, 0.72017705,
        0.37047226]])